print('(Preguntas) Primera Practica')
print('1.¿Cuales son los dos valores del tipo de datos booleano?')
print('  True and False')
print('2.¿Cuales son los tres operadores booleanos?')
print('  And, Or y Not')
print('3.¿Cuales son los 6 operadores de comparación?')
print('   ==, !=, >, >=, <=, <,')
print('4.¿Cual es la diferencia entre el operador igual y el de asignacion?')
print('  Como su nombre lo indica. el operdor de asignación (=) sirve para asignar un valor a una variable mientras que el de    igualdad (==) sirve para evaluar si dos valores son iguales, no importanto que sean del mismo tipo de dato')
print('5.Explique es que es una condicion y donde la usaria')
print('  El condicionante es una parte fundamental de la programacion pues con ella se puede indicar a la maquina que hacer en   diferentes circunsatancias a traves de "condiciones"')
print('6.¿Que puede hacer si su programa esta atascado en un bucle infinito?')
print('  Una vez que se ha entrado en un bucle infinito, se puede salir de este oprimiendo la tecla "Ctrl" y dos veces la tecla "C", sin embargo, la mejor manera de hacerlo es abriendo otra terminal e ingresar el comando "TOP" para despues          escribir la telca "K" seguida del ID del proceso (por ejemplo 1618)')
print('7.¿Cual es la difrencia entre romper y continuar?')
print('  "break" se utiliza para interrumpir el flujo de control dentro de un bucle, es por ello que va despues de un            condicionante como "if" pues despues de que se cumpla dicha condicion, el bucle cerrara.')
print('  "continue" tambien se ejecuta dentro de un bucle pero en este caso, el bucle continua, omitiendo solo los valores que    sirvieron como condicionante para el continue"')
print('8.¿Cual es la diferencia entre rango (10), rango (0, 10) y rango (0, 10, 1)?')
print('   Ninguna, pues los tres rangos mostraran lo mismo, los numero del 0 al 9 de uno en uno en forma de lista, sin embargo    en el caso general, los rangos del tipo (a) muestran los numeros enlistados empezando desde 0 hasta llegar a "a"-1      por otro lado, los rangos del tipo (a,b) enlistaran los numeros empezando en "a" hasta llegar a "b"-1. Por ultimo,      los rangos de la forma (a,b,c) muestran la lista de numero empezando en "a" hasta llegar a "b"-1 pero avanzando en      intervalo de "c", no de uno en uno como en los casos anteriores"') 

